import type { Metadata } from "next";
import { Bricolage_Grotesque } from 'next/font/google';
import { SessionProvider } from "next-auth/react";
import { auth } from "../../auth";

import "./globals.css";
import { LogCartProvider } from "../context/InfluencersContext";
import { LogpackageProvider } from "../context/PackagesContext";
import { CartProvider } from "../context/CartContext";
import { ToastProvider } from "../components/toast";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import Toast from "../components/ui/toster";


const bricolage = Bricolage_Grotesque({
  subsets: ['latin'],
  variable: '--font-bricolage',
});


export const metadata: Metadata = {
  title: "Ampli5 | AI-Powered influencer & PR solutions for web3",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en" className={`scroll-smooth`}>
      <head>
      </head>
      <body className={`${bricolage.variable}`}>
        <Toast />
        <ToastProvider />
        <SessionProvider session={session}>
          <CartProvider>
            <LogCartProvider>
              <LogpackageProvider>
                <Navbar />
                <div className="h-[65px] lg:h-80px w-full bg-black"></div>
                <div className="min-h-[calc(100vh_-_295px)] bg-cream-bg">{children}</div>
                <Footer />
              </LogpackageProvider>
            </LogCartProvider>
          </CartProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
